#!/usr/bin/env python3
"""E1.2 & E1.3 — External-LM Quality Metric and C5 Rerun.

Uses distilgpt2 to independently score text generated by the toy model,
removing the confound of decoder collapse.
"""

import json
import sys
import time
import math
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SRC_DIR = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(SRC_DIR))

from modules.model import ELF
from utils.sampling_utils import net_out_to_v_x, get_sampling_steps

RESULTS_DIR = Path(__file__).resolve().parent / "results"
DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"

T_EPS = 0.05
SIGMA = 1.0
N_SAMPLES = 32
STEP_BUDGETS = [4, 8, 16, 32, 64]
TIME_SCHEDULES = ["uniform", "logit_normal"]


def load_detokenizer():
    map_path = RESULTS_DIR / "detokenizer_map.json"
    if not map_path.exists():
        print("❌ Detokenizer map not found. Run E1.1 first.")
        sys.exit(1)
    with open(map_path, "r") as f:
        d_map = json.load(f)
    # Convert keys back to int
    return {int(k): v for k, v in d_map.items()}

def decode_tokens_to_text(token_ids, detok_map):
    """E1.1: Convert sequence of pseudo-token IDs to text."""
    words = []
    for tid in token_ids:
        tid = int(tid)
        if tid in detok_map:
            word = detok_map[tid]
            # Handle special T5 spacing
            if word.startswith(' '):
                words.append(' ' + word[1:])
            else:
                words.append(word)
    # Join and clean up double spaces
    text = "".join(words).replace("  ", " ").strip()
    return text

def setup_external_lm():
    from transformers import GPT2LMHeadModel, GPT2TokenizerFast
    print(f"Loading distilgpt2 on {DEVICE}...")
    tokenizer = GPT2TokenizerFast.from_pretrained("distilgpt2")
    model = GPT2LMHeadModel.from_pretrained("distilgpt2").to(DEVICE).eval()
    return model, tokenizer

def score_text(text: str, model, tokenizer, device=DEVICE) -> float:
    """E1.2: Score text perplexity using external LM."""
    if not text.strip():
        return float('inf')
    
    encodings = tokenizer(text, return_tensors="pt")
    input_ids = encodings.input_ids.to(device)
    
    if input_ids.shape[1] < 2:
        return float('inf') # Need at least 2 tokens for a target
        
    with torch.no_grad():
        outputs = model(input_ids, labels=input_ids)
        loss = outputs.loss
    return math.exp(loss.item())

def run_sanity_checks(lm_model, lm_tokenizer, detok_map):
    print("\n── Sanity Checks (E1.2) ──")
    # a) Real text
    real_texts = [
        "The quick brown fox jumps over the lazy dog.",
        "Artificial intelligence is transforming the world.",
        "A successful experiment requires careful measurement and controls."
    ]
    print("Real text perplexities:")
    real_ppls = []
    for t in real_texts:
        ppl = score_text(t, lm_model, lm_tokenizer)
        real_ppls.append(ppl)
        print(f"  {ppl:6.1f} | '{t}'")
        
    # b) Random decoded tokens
    rng = np.random.default_rng(42)
    print("Random pseudo-token perplexities:")
    random_ppls = []
    vocab_size = len(detok_map)
    for _ in range(3):
        tids = rng.integers(0, vocab_size, size=16)
        t = decode_tokens_to_text(tids, detok_map)
        ppl = score_text(t, lm_model, lm_tokenizer)
        random_ppls.append(ppl)
        print(f"  {ppl:6.1f} | '{t}'")
        
    avg_real = np.mean(real_ppls)
    avg_rand = np.mean(random_ppls)
    
    if avg_rand > avg_real * 10:
        print(f"✅ Sanity check PASS: Random text PPL ({avg_rand:.1f}) >> Real text PPL ({avg_real:.1f})")
        return True
    else:
        print(f"❌ Sanity check FAIL: Metric does not separate real from random!")
        return False


def load_real_checkpoint():
    ckpt_path = Path(__file__).resolve().parent.parent / "phase0c" / "results" / "mini_elf_real_checkpoint.pt"
    if not ckpt_path.exists():
        print(f"❌ Real checkpoint not found.")
        sys.exit(1)
    ckpt = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
    cfg = ckpt["config"]
    model = ELF(
        text_encoder_dim=cfg["encoder_dim"], max_length=cfg["max_length"],
        hidden_size=cfg["hidden_size"], depth=cfg["depth"],
        num_heads=cfg["num_heads"], mlp_ratio=cfg["mlp_ratio"],
        bottleneck_dim=cfg["bottleneck_dim"], num_time_tokens=2,
        num_self_cond_cfg_tokens=0, num_model_mode_tokens=2,
        vocab_size=cfg["vocab_size"],
    )
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(DEVICE).eval()
    return model, cfg

# ── Samplers ──

def ode_sample(model, n_samples, n_steps, encoder_dim, seq_len,
               time_schedule="uniform", device="cpu", initial_noise=None):
    dtype = next(model.parameters()).dtype
    with torch.no_grad():
        z = initial_noise.clone().to(device)
        steps = get_sampling_steps(n_steps, time_schedule=time_schedule, device=device, dtype=dtype)
        for i in range(n_steps):
            t_curr, t_next = float(steps[i]), float(steps[i+1])
            h = t_next - t_curr
            t_batch = torch.full((n_samples,), t_curr, dtype=dtype, device=device)
            net_out, _ = model(z, t_batch, deterministic=True, decoder_step_active=None)
            v_pred, _ = net_out_to_v_x(net_out, z, t_batch, T_EPS)
            z = z + h * v_pred
    return z

def elf_sde_sample(model, n_samples, n_steps, encoder_dim, seq_len,
                   gamma=0.5, time_schedule="uniform", device="cpu",
                   initial_noise=None):
    dtype = next(model.parameters()).dtype
    with torch.no_grad():
        z = initial_noise.clone().to(device)
        steps = get_sampling_steps(n_steps, time_schedule=time_schedule, device=device, dtype=dtype)
        for i in range(n_steps):
            t_curr, t_next = float(steps[i]), float(steps[i+1])
            h = t_next - t_curr
            alpha = max(0.0, min(1.0, 1.0 - gamma * h))
            t_back = alpha * t_curr
            if gamma > 0:
                eps = torch.randn_like(z)
                z_back = alpha * z + (1.0 - alpha) * eps
            else:
                z_back = z
            t_batch = torch.full((n_samples,), t_back, dtype=dtype, device=device)
            net_out, _ = model(z_back, t_batch, deterministic=True, decoder_step_active=None)
            v_pred, _ = net_out_to_v_x(net_out, z_back, t_batch, T_EPS)
            z = z_back + (t_next - t_back) * v_pred
    return z

def corrected_sde_sample(model, n_samples, n_steps, encoder_dim, seq_len,
                         g=0.5, time_schedule="uniform", device="cpu",
                         initial_noise=None):
    dtype = next(model.parameters()).dtype
    with torch.no_grad():
        z = initial_noise.clone().to(device)
        steps = get_sampling_steps(n_steps, time_schedule=time_schedule, device=device, dtype=dtype)
        for i in range(n_steps):
            t_curr, t_next = float(steps[i]), float(steps[i+1])
            h = t_next - t_curr
            t_batch = torch.full((n_samples,), t_curr, dtype=dtype, device=device)
            net_out, _ = model(z, t_batch, deterministic=True, decoder_step_active=None)
            _, x_pred = net_out_to_v_x(net_out, z, t_batch, T_EPS)
            denom_v = max(1 - t_curr, T_EPS)
            v = (x_pred - z) / denom_v
            denom_s = max(1 - t_curr, T_EPS)**2 * SIGMA**2
            score = (t_curr * x_pred - z) / denom_s
            drift = v + (g**2 / 2) * score
            noise = torch.randn_like(z) if g > 0 else 0.0
            diffusion = g * math.sqrt(abs(h)) * noise if g > 0 else 0.0
            z = z + h * drift + diffusion
    return z

def get_tokens(model, z, device):
    """Convert z to token IDs via the model's decoder head."""
    model.eval()
    dtype = next(model.parameters()).dtype
    with torch.no_grad():
        t_final = torch.ones(z.shape[0], dtype=dtype, device=device)
        _, logits = model(z.to(device), t_final, deterministic=True,
                          decoder_step_active=torch.ones(z.shape[0], device=device))
        tokens = logits.argmax(dim=-1).cpu().numpy()
    return tokens


def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    print("=" * 60)
    print("E1.3 — External-LM Quality Metric (distilgpt2)")
    print("=" * 60)

    # Load detokenizer and models
    detok_map = load_detokenizer()
    lm_model, lm_tokenizer = setup_external_lm()
    
    if not run_sanity_checks(lm_model, lm_tokenizer, detok_map):
        sys.exit(1)

    elf_model, cfg = load_real_checkpoint()
    encoder_dim = cfg["encoder_dim"]
    seq_len = cfg["max_length"]

    sampler_configs = [
        {"name": "ODE", "fn": lambda ns, sched, noise:
            ode_sample(elf_model, N_SAMPLES, ns, encoder_dim, seq_len,
                       time_schedule=sched, device=DEVICE, initial_noise=noise)},
        {"name": "ELF-SDE γ=0.5", "fn": lambda ns, sched, noise:
            elf_sde_sample(elf_model, N_SAMPLES, ns, encoder_dim, seq_len,
                           gamma=0.5, time_schedule=sched, device=DEVICE, initial_noise=noise)},
        {"name": "ELF-SDE γ=1.0", "fn": lambda ns, sched, noise:
            elf_sde_sample(elf_model, N_SAMPLES, ns, encoder_dim, seq_len,
                           gamma=1.0, time_schedule=sched, device=DEVICE, initial_noise=noise)},
        {"name": "Corrected-SDE g=0.5", "fn": lambda ns, sched, noise:
            corrected_sde_sample(elf_model, N_SAMPLES, ns, encoder_dim, seq_len,
                                 g=0.5, time_schedule=sched, device=DEVICE, initial_noise=noise)},
        {"name": "Corrected-SDE g=1.0", "fn": lambda ns, sched, noise:
            corrected_sde_sample(elf_model, N_SAMPLES, ns, encoder_dim, seq_len,
                                 g=1.0, time_schedule=sched, device=DEVICE, initial_noise=noise)},
    ]

    all_results = {}
    n_runs = 3

    for sched in TIME_SCHEDULES:
        print(f"\n  ═══ {sched} ═══")
        sched_results = {}
        for scfg in sampler_configs:
            name = scfg["name"]
            print(f"    {name}:")
            step_results = {}
            for n_steps in STEP_BUDGETS:
                ppls, divs = [], []
                for run in range(n_runs):
                    torch.manual_seed(42 + run)
                    noise = torch.randn(N_SAMPLES, seq_len, encoder_dim,
                                        dtype=torch.float32, device=DEVICE)
                    z_final = scfg["fn"](n_steps, sched, noise)
                    tokens = get_tokens(elf_model, z_final, DEVICE)
                    
                    # Compute Diversity and PPL
                    unique_per_seq = [len(np.unique(tokens[i])) for i in range(tokens.shape[0])]
                    divs.append(np.mean(unique_per_seq))
                    
                    batch_ppls = []
                    for i in range(N_SAMPLES):
                        text = decode_tokens_to_text(tokens[i], detok_map)
                        p = score_text(text, lm_model, lm_tokenizer, DEVICE)
                        if not math.isinf(p) and not math.isnan(p):
                            batch_ppls.append(p)
                    
                    if batch_ppls:
                        ppls.append(np.mean(batch_ppls))
                    else:
                        ppls.append(float('inf'))

                step_results[str(n_steps)] = {
                    "ppl_mean": float(np.mean(ppls)),
                    "ppl_std": float(np.std(ppls)),
                    "diversity_mean": float(np.mean(divs)),
                }
                print(f"      steps={n_steps:3d}: "
                      f"PPL={np.mean(ppls):.1f}±{np.std(ppls):.1f}, "
                      f"div={np.mean(divs):.1f}")
            sched_results[name] = step_results
        all_results[sched] = sched_results


    # Plotting
    fig, axes = plt.subplots(2, 2, figsize=(15, 11))
    colors = {
        "ODE": "#4C72B0", "ELF-SDE γ=0.5": "#55A868", "ELF-SDE γ=1.0": "#8172B2",
        "Corrected-SDE g=0.5": "#C44E52", "Corrected-SDE g=1.0": "#DD8452",
    }
    markers = {"ODE": "o", "ELF-SDE γ=0.5": "s", "ELF-SDE γ=1.0": "D",
               "Corrected-SDE g=0.5": "^", "Corrected-SDE g=1.0": "v"}

    for col, sched in enumerate(TIME_SCHEDULES):
        sd = all_results[sched]
        # PPL
        ax = axes[0][col]
        for name, data in sd.items():
            steps = sorted([int(s) for s in data.keys()])
            ppl_m = [data[str(s)]["ppl_mean"] for s in steps]
            ppl_s = [data[str(s)]["ppl_std"] for s in steps]
            ax.errorbar(steps, ppl_m, yerr=ppl_s, fmt=f"{markers[name]}-",
                        color=colors[name], lw=2, markersize=7, label=name,
                        capsize=3, alpha=0.85)
        ax.set_xlabel("Steps"); ax.set_ylabel("External PPL (↓ better)")
        ax.set_title(f"Gen PPL (distilgpt2) — {sched}", fontsize=11)
        ax.legend(fontsize=7); ax.grid(True, alpha=0.3)
        ax.set_xscale("log", base=2)
        # Only view reasonable PPL range to avoid infinite scaling from collapse
        ax.set_ylim(0, 50000)

        # Diversity
        ax = axes[1][col]
        for name, data in sd.items():
            steps = sorted([int(s) for s in data.keys()])
            divs = [data[str(s)]["diversity_mean"] for s in steps]
            ax.plot(steps, divs, f"{markers[name]}-", color=colors[name],
                    lw=2, markersize=7, label=name, alpha=0.85)
        ax.set_xlabel("Steps"); ax.set_ylabel("Unique Tokens (↑ better)")
        ax.set_title(f"Diversity — {sched}", fontsize=11)
        ax.legend(fontsize=7); ax.grid(True, alpha=0.3)
        ax.set_xscale("log", base=2)

    plt.suptitle("E1.3: Step-Budget Comparison (External PPL Metric)",
                 fontsize=14, y=1.02)
    plt.tight_layout()
    plt.savefig(RESULTS_DIR / "testE1_external_quality_step_budget.png", dpi=150, bbox_inches="tight")
    plt.close()
    
    with open(RESULTS_DIR / "testE1_external_quality_step_budget.json", "w") as f:
        json.dump(all_results, f, indent=2)

    print(f"\n  Saved → {RESULTS_DIR / 'testE1_external_quality_step_budget.png'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
